spring:
  profiles:
    active: dev
    #接口返回对象中的日期格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      static-locations: classpath:/static
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

mybatis:
  #mapper.xml存放路径（resource）
  mapper-locations: classpath:mapper/*.xml
  #mapper接口文件存放路径
  type-aliases-package: com.example.springboottest.mapper

#引入日志文件
logging:
  config: classpath:config/logback-spring.xml


